### ISSUE TITLE
Interface 'DatabaseSnapshotExists<T>' incorrectly extends interface 'DataSnapshot'

### ISSUE THREAD

**Issue by wojteko22** [angular/angularfire#3255]
### Version info

**Angular:** 14.1.1

**Firebase:** 9.9.2

**AngularFire:** 7.4.1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Stackblitz demonstrating the problem**
https://github.com/wojteko22/angular-fire-bug

**Steps to set up and reproduce**
1. Clone repo
2. `npm install`
3. `ng serve`

**Sample data and security rules**

### Debug output

** Errors in the JavaScript console **
```
Error: node_modules/@angular/fire/compat/database/interfaces.d.ts:47:18 - error TS2430: Interface 'DatabaseSnapshotExists<T>' incorrectly extends interface 'DataSnapshot'.
  Types of property 'forEach' are incompatible.
    Type '(action: (a: DatabaseSnapshot<T>) => boolean) => boolean' is not assignable to type '(action: (a: DataSnapshot & { key: string; }) => boolean | void) => boolean'.
      Types of parameters 'action' and 'action' are incompatible.
        Types of parameters 'a' and 'a' are incompatible.
          Type 'DatabaseSnapshot<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
            Type 'DatabaseSnapshotExists<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
              Type 'DatabaseSnapshotExists<T>' is not assignable to type 'DataSnapshot'.
                Types of property 'forEach' are incompatible.
                  Type '(action: (a: DatabaseSnapshot<T>) => boolean) => boolean' is not assignable to type '(action: (a: DataSnapshot & { key: string; }) => boolean | void) => boolean'.
                    Types of parameters 'action' and 'action' are incompatible.
                      Types of parameters 'a' and 'a' are incompatible.
                        Type 'DatabaseSnapshot<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
                          Type 'DatabaseSnapshotDoesNotExist<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
                            Type 'DatabaseSnapshotDoesNotExist<T>' is not assignable to type '{ key: string; }'.
                              Types of property 'key' are incompatible.
                                Type 'string | null' is not assignable to type 'string'.
                                  Type 'null' is not assignable to type 'string'.

47 export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
                    ~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@angular/fire/compat/database/interfaces.d.ts:52:18 - error TS2430: Interface 'DatabaseSnapshotDoesNotExist<T>' incorrectly extends interface 'DataSnapshot'.
  Types of property 'forEach' are incompatible.
    Type '(action: (a: DatabaseSnapshot<T>) => boolean) => boolean' is not assignable to type '(action: (a: DataSnapshot & { key: string; }) => boolean | void) => boolean'.
      Types of parameters 'action' and 'action' are incompatible.
        Types of parameters 'a' and 'a' are incompatible.
          Type 'DatabaseSnapshot<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
            Type 'DatabaseSnapshotDoesNotExist<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
              Type 'DatabaseSnapshotDoesNotExist<T>' is not assignable to type 'DataSnapshot'.
                Types of property 'forEach' are incompatible.
                  Type '(action: (a: DatabaseSnapshot<T>) => boolean) => boolean' is not assignable to type '(action: (a: DataSnapshot & { key: string; }) => boolean | void) => boolean'.
                    Types of parameters 'action' and 'action' are incompatible.
                      Types of parameters 'a' and 'a' are incompatible.
                        Type 'DatabaseSnapshot<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
                          Type 'DatabaseSnapshotExists<T>' is not assignable to type 'DataSnapshot & { key: string; }'.
                            Type 'DatabaseSnapshotExists<T>' is not assignable to type '{ key: string; }'.
                              Types of property 'key' are incompatible.
                                Type 'string | null' is not assignable to type 'string'.
                                  Type 'null' is not assignable to type 'string'.

52 export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

### Expected behavior

No error in console

### Actual behavior

Error in console

### Reason
The reason of this error is change of `forEach()` signature of firebase.database.DataSnapshot in firebase@9.9.2

These are interfaces from @angular/fire:
```
export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
    exists(): true;
    val(): T;
    forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
}
export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
    exists(): false;
    val(): null;
    forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
}
```

In firebase@9.9.2 firebase.database.DataSnapshot has such method:
```
forEach(
  action: (
    a: firebase.database.DataSnapshot & { key: string }
  ) => boolean | void
): boolean;
```

In firebase@9.9.1 it was:
```
forEach(
  action: (a: firebase.database.DataSnapshot) => boolean | void
): boolean;
```

**Comment by iurydev** [comment]
I have the same problem today. Any news about it ? I went back to version 9.9.1 to resolve.

**Comment by Ahsanali012** [comment]
Still facing this issue

**Comment by michelcasilla** [comment]
Same here

**Comment by TroniPM** [comment]
Same here. Any ideas?

**Comment by jpb-sophia** [comment]
Firebase: 9.9.2

I solved the issue by modifying this file like this:

[my project path]\node_modules\@angular\fire\compat\database\interfaces.d.ts

```
export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
  exists(): true;
  val(): T;
  // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
  forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
}
export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
  exists(): false;
  val(): null;
  // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
  forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
}
```

Then, I was able to read/write to the Firebase "Realtime Database".

**Comment by SeafAbuFares** [comment]
> 

Ty so much it worked for me

**Comment by TroniPM** [comment]
> Firebase: 9.9.2
> 
> I solved the issue by modifying this file like this:
> 
> [my project path]\node_modules\\@angular\fire\compat\database\interfaces.d.ts
> 
> ```
> export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
>   exists(): true;
>   val(): T;
>   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
>   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> }
> export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
>   exists(): false;
>   val(): null;
>   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
>   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> }
> ```
> 
> Then, I was able to read/write to the Firebase "Realtime Database".

The problem about this is: I can't use that workaround in production because CI/CD pipeline. 😔

**Comment by Low-Hiss-Systems** [comment]
Any news on this? The workaround provided does work for me in development but like the user above I can't deploy it to production

**Comment by orbanszlrd** [comment]
I had a similar issue, but only using the latest version of typescript (4.8.2) which is not officially supported by Angular for now.

**Comment by AlexRebula** [comment]
The only way I could make this work was by setting compilerOptions.strict (tsconfig.json) to "false". Does anyone have a better idea? I suppose it's a problem in the fire library itself and unless that is fixed in there, there is not much we can do?

**Comment by jlgarcia-vs** [comment]
The same error is happening in "node_modules/@angular/fire/compat/firestore/interfaces.d.ts" with latest version.

**Comment by NoxSensei** [comment]
I've set `skipLibcheck` in the `tsconfig.json` to avoid checking libraries. But it's just a temporary hack to ignore errors.
```json
"skipLibCheck": true
```

**Comment by hiredtocode** [comment]
> 
Before doing these things my app wouldn't build but now it builds.

**Comment by gorden0929** [comment]
Same here
Temporarily solution for me:
Downgrade typescript to `4.7.4`

**Comment by wojteko22** [comment]
The problem is solved with `firebase@9.9.3`
`firebase.database.DataSnapshot` again has method:
```
forEach(
  action: (a: firebase.database.DataSnapshot) => boolean | void
): boolean;
```
instead of 
```
forEach(
  action: (
    a: firebase.database.DataSnapshot & { key: string }
  ) => boolean | void
): boolean;
```
as in `firebase@9.9.2`

**Comment by vpease** [comment]
Same error trying to use Firestore
I am using  
@angular/fire@7.4.1 
typescript@4.8.4
firebase@9.13.0

My workaround was to downgrade typescript to 4.7.4

**Comment by Haytham510** [comment]
Same issue with me 
I am using versions:

@angular/fire@7.4.1
typescript@4.6.4
firebase@9.9.2

I cannot update these versions because I am working with a team and this error doesn't occur with any of them.
What could be the problem with my local environment?

**Comment by kedevked** [comment]
I have ` "firebase": "^9.14.0",` and the issue is still there

**Comment by mikkimichaelis** [comment]
Same issue

 "@angular/core": "^15.0.0",
"@angular/fire": "^7.5.0",
 "firebase": "^9.14.0",
 "typescript": "~4.8.4"

used the previously mentioned temp fix

"skipLibCheck": true -> tsconfig.json

WTF?

**Comment by isNotOkay** [comment]
Same issue here with Angular 15, any updates on this?

**Comment by edarioq** [comment]
Same issue, NG `15.0.0` - seems to be an issue with compatability interfaces `@angular/fire/compat/firestore/interfaces.d.ts`.

**Comment by armaanbanoriya** [comment]
A Big stop for the project.

 "@angular/core": "^15.0.0",
"firebase": "^9.15.0",
"@angular/fire": "^7.5.0",
"typescript": "~4.8.2"

**Comment by SotoSen** [comment]
Same @armaanbanoriya not working...

> 

This works, thank you.  (angular 15, fire 7.5 & firebase 9.9.3)

**Comment by cwaj400** [comment]
> Same issue, using angular `15.0.0` - seems to be an issue with compatibility interfaces `@angular/fire/compat/firestore/interfaces.d.ts`.
> 
> This is **momentarily** fixed by changing the above file, replacing line numbers 15 and 24 to:
> 
> ```
> data(options?: SnapshotOptions): any;
> ```

Is it worth doing a PR for this?

**Comment by potatoman009** [comment]
Angular 15 dosen't with any version of firebase, as a hack u can change "strict" to false in tsconfig.json file. Team please fix this

**Comment by Andrew3005** [comment]
> > Same issue, using angular `15.0.0` - seems to be an issue with compatibility interfaces `@angular/fire/compat/firestore/interfaces.d.ts`.
> > This is **momentarily** fixed by changing the above file, replacing line numbers 15 and 24 to:
> > ```
> > data(options?: SnapshotOptions): any;
> > ```
> 
> Is it worth doing a PR for this? It resoled my issue too.

It works, but if I use firebase hosting, I get error due of this and I cant build project and deploy it
only if to deploy it by hands

**Comment by Jbz797** [comment]
> It works, but if I use firebase hosting, I get error due of this and I cant build project and deploy it only if to deploy it by hands

This is normal I think because Firebase will not take into account the modification you made locally. If the PR is merge then there will be no problem.

**Comment by tbenson89** [comment]
Newb here, I feel like i'm running in circles chasing my tail anyone got a production grade hack? 

"@angular/fire": "^7.5.0",
"firebase": "^9.15.0",
"typescript": "~4.8.4"

Sorry if my comment is stupid i'm dumb and don't really communicate very well in forums just read them usually but this is driving me bonkers. I have to get it working I really want this project to launch using firebase tools :)

**Comment by danielcornejo14** [comment]
Hi, if you are still having this problem maybe you can read this issue https://github.com/angular/angularfire/issues/3290, it solved the problem for me

**Comment by hezyz** [comment]
SOLUTION 
angular/fire 7.5.0 firebase 9.16.0
go to interfaces.d.ts the file that generates the error
add at the end of the error row <T>
`export interface QueryDocumentSnapshot<T> extends firebase.firestore.QueryDocumentSnapshot<T> `
do for all 3 errors

**Comment by david2242** [comment]
> SOLUTION angular/fire 7.5.0 firebase 9.16.0 go to interfaces.d.ts the file that generates the error add at the end of the error row `<T>` `export interface QueryDocumentSnapshot<T> extends firebase.firestore.QueryDocumentSnapshot<T> ` do for all 3 errors

This helped me as well! Thank you!

**Comment by igor-augustynski-furba** [comment]
Have this problem too. Currently setting `"skipLibCheck": true` seems the best option. 
It's always fun with AngularFire.

**Comment by david2242** [comment]
> 

You should open a PR with this. I think this is the finest fix.

**Comment by david2242** [comment]
> SOLUTION angular/fire 7.5.0 firebase 9.16.0 go to interfaces.d.ts the file that generates the error add at the end of the error row `<T>` `export interface QueryDocumentSnapshot<T> extends firebase.firestore.QueryDocumentSnapshot<T> ` do for all 3 errors

You should open a PR with this. I think it is a nice fix.

**Comment by esolioz** [comment]
Hi! I have the same issue. I am actually using the following version : 
- Angular v16.0.3
- Typescript v5.0.4
- Firebase v9.22.2

I hade the following, in tsconfig : 
"skipLibCheck": true 

as suggest by @igor-augustynski-furba

**Comment by KevinVanH** [comment]
For me this happened when using the newer firestorm (from '@angular/fire/firestore'), while also importing the compat firestorm somewhere (from "@angular/fire/compat/firestore). For me to solution was to only ever use one of the two in my project.

**Comment by ek1mb4** [comment]
> The only way I could make this work was by setting compilerOptions.strict (tsconfig.json) to "false". Does anyone have a better idea? I suppose it's a problem in the fire library itself and unless that is fixed in there, there is not much we can do?

I suggest you, instead of this, add // @ts-ignore and every line that is preceded with this decorator will be ignored and at the end you keep your ability to spot errors along your project with option strict.

**Comment by moueza** [comment]
I have same trace after npm update in V15,  but without any calling file .ts ref in the trace, so I don't know what to isolate, comment ?

**Comment by diegolaciar** [comment]
"@angular/fire": "^7.6.1",
"@angular/core": "^16.0.0",

I don't like it but for the moment i did:

"skipLibCheck": true

and it works.

**Comment by urban-hostel** [comment]
> For me this happened when using the newer firestorm (from '@angular/fire/firestore'), while also importing the compat firestorm somewhere (from "@angular/fire/compat/firestore). For me to solution was to only ever use one of the two in my project.

This fixed it for me
Firebase introduced a modular SDK with v9, which is tree-shakeable, and therefore, more efficient in terms of bundle size. @angular/fire followed this change by providing a way to use both the older and the newer versions, using @angular/fire/compat for the older version.
 
Use your IDE's search functionality to find all instances where you're importing from @angular/fire/compat/firestore. If you've decided to use the newer SDK, replace these with @angular/fire/firestore.
 
For example in the app.module,ts

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

// Modern Angular Fire imports
import { provideFirebaseApp, getApp, initializeApp } from '@angular/fire/app';
import { getFirestore, provideFirestore } from '@angular/fire/firestore';
import { getAuth, provideAuth } from '@angular/fire/auth';
import { getStorage, provideStorage } from '@angular/fire/storage';
import { getDatabase, provideDatabase } from '@angular/fire/database';

import { AngularMaterialModule } from './modules/angular-material.module';
import { AppRoutingModule } from './modules/app-routing.module';

import { environment } from '../environments/environment';

import { AppComponent } from './app.component';
import { HelloWorldComponent } from './pages/hello-world/hello-world.component';
import { CoreComponent } from './pages/core/core.component';

@NgModule({
  declarations: [
    AppComponent,
    HelloWorldComponent,
    CoreComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    AngularMaterialModule,
    
    // Firebase Initialization
    provideFirebaseApp(() => initializeApp(environment.firebaseConfig)),
    provideAuth(() => getAuth()),
    provideFirestore(() => getFirestore()),
    provideStorage(() => getStorage()),
    provideDatabase(() => getDatabase())
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Now, when you want to use Firestore, Auth, or any other Firebase service in your components or services, you'd inject them using Angular's DI system. For example, with Firestore:

```
import { Component, OnInit } from '@angular/core';
import { AngularFirestore } from '@angular/fire/firestore'; // This import will remain the same for convenience

@Component({
  selector: 'app-some-component',
  template: `...`,
  styleUrls: ['...']
})
export class SomeComponent implements OnInit {
  constructor(private firestore: AngularFirestore) {}

  ngOnInit() {
    // Use this.firestore here
  }
}
 

```

**Comment by abhijitgayen** [comment]
i am facing same problem here

**Comment by WhooperDar** [comment]
thanks for the solution

**Comment by gonzalezzccamila** [comment]
> export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
>   exists(): true;
>   val(): T;
>   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
>   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> }
> export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
>   exists(): false;
>   val(): null;
>   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
>   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> }

LITERALLY SAVED MY LIFE TYSM <3

**Comment by oussama-harrathi** [comment]
> > Firebase: 9.9.2
> > I solved the issue by modifying this file like this:
> > [my project path]\node_modules\@angular\fire\compat\database\interfaces.d.ts
> > ```
> > export interface DatabaseSnapshotExists<T> extends firebase.database.DataSnapshot {
> >   exists(): true;
> >   val(): T;
> >   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
> >   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> > }
> > export interface DatabaseSnapshotDoesNotExist<T> extends firebase.database.DataSnapshot {
> >   exists(): false;
> >   val(): null;
> >   // forEach(action: (a: DatabaseSnapshot<T>) => boolean): boolean;
> >   forEach(action: (a: firebase.database.DataSnapshot & { key: string }) => boolean | void): boolean;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, I was able to read/write to the Firebase "Realtime Database".
> 
> The problem about this is: I can't use that workaround in production because CI/CD pipeline. 😔

did you find any solution pls i still have the error now

**Comment by redafillali** [comment]
> Problem still occurs. I've set `skipLibcheck` in the `tsconfig.json` to avoid checking libraries. But it's just a temporary hack to ignore errors.
> 
> ```json
> "skipLibCheck": true
> ```

add 
```
    "skipLibCheck": true,
    "strictPropertyInitialization": false,
    "noImplicitAny": false
```
 After
` "useDefineForClassFields": false`

**Comment by WERMAR** [comment]
I used firebase version 10.13.0 and the issue still exists. Based on this thread https://stackoverflow.com/questions/73281199/error-when-importing-angularfiredatabasemodule it should be fixed in 9.9.3 or newer - does anyone has the same problems?
